### ISSUE TITLE
Cannot subscripe to newsletter with Firefox Tracking Protection enabled

### ISSUE THREAD

**Issue by jnachtigall** [RecordReplay/website#17]
On https://webreplay.io/contact.html the newsletter subscription does not work with Tracking Protection (enabled by default, I think I have `strict` mode).

![grafik](https://user-images.githubusercontent.com/3307404/74220345-a2a60b00-4caf-11ea-9bb1-d35cee193cc5.png)

See the console warnings about the blocking. 

After disabling Firefox' Tracking Protection and UBlock Origin, then it worked.

**Comment by jnachtigall** [comment]
Also would be good if the newsletter was a bit more highlighted. I missed it the first time when hitting the contact page, and only noticed there's a newsletter in one of the slack.
Maybe make it a bit more colorful, maybe also move it to the top of the contact page for now.

**Comment by bhackett1024** [comment]
Thanks for the feedback, the issue with tracking protection is pretty unfortunate.  I think that the email list platform we use (Mailchimp, which is popular with small businesses) is blacklisted by Firefox's strict tracking protection, probably because it can be used to track email opens and link clicks (we don't use these features).  Blocking the signup form seems excessive to me but I don't think there's much that can be done other than using a different email list platform.

**Comment by jnachtigall** [comment]
The way it is handled for other CMS is that mailchimp form is delivered via the original domain, which then forwards to mailchimp. So there's no third-party domain inclusion / network request in the html needed.

I guess every other email platform might have the same problem.

I think you use netlify. Maybe https://functions.netlify.com/ would help

> For example, you can have a script that sends event data to google analytics, or adds someone to a mailchimp list, or sends a request to a zapier webhook.

There are some examples on https://functions.netlify.com/examples?search=mailchimp

Second link to "Mailchimp signup flow" example is broken unfortunately 
https://github.com/netlify/functions/issues/44

But the 3rd link "Progressive Mailchimp subscription form" looks like what you've want to use
